### ISSUE TITLE
Error if picture does not exist 

### ISSUE THREAD

**Issue by DanielHabenicht** [kirkone/KK.AspNetCore.Images#1]
If requesting a picture that does not exist in the source folder the Middleware crashes.

![image](https://user-images.githubusercontent.com/13590797/52777585-72983d80-3044-11e9-8825-da718bc10050.png)

It should return a 404. 
This does also extend to pictures with the wrong file type. (e.g. `.png` instead of `.jpg`)

Version: 0.1.1

**Comment by DanielHabenicht** [comment]
Is there a way to automatically convert the pictures into the requested file type?

**Comment by kirkone** [comment]
not at the moment. I think this is more complicated. The file ending will not provide enough information to the the image automatically converted.
I started with support for more file types in the configuration but for now I want to complete jpeg first.

I will have a look into the error.

Thanks for the feedback
